apiVersion: apps/v1
kind: Deployment
metadata:
  name: xhip-backend
  labels:
    app: xhip-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xhip-backend
  template:
    metadata:
      labels:
        app: xhip-backend
    spec:
      containers:
        - name: xhip-backend
          image: rithik933/xhip-backend:v1
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_SERVER
              valueFrom:
                secretKeyRef:
                  name: mongodb-configmap
                  key: db_host
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
