apiVersion: v1
kind: Service
metadata:
  name: xhip-backend
spec:
  type: LoadBalancer  
  selector:
    app: xhip-backend
  ports:
    - protocol: TCP
      port: 80 # service to external traffic
      targetPort: 3000 