FROM node:20-alpine
ARG DATABASE_URL
ARG REDIS_URI

RUN set -ex; \
    apk update; \
    apk add --no-cache \
    openssl

WORKDIR /usr/src/app

COPY . .

RUN npm i pnpm -g
RUN pnpm install

RUN cd packages/database && DATABASE_URL=$DATABASE_URL npx prisma generate && cd ../..

RUN echo DATABASE_URL=$DATABASE_URL >> apps/worker/.env
RUN DATABASE_URL=$DATABASE_URL && REDIS_URI=$REDIS_URI cd apps/worker && pnpm build && cd ../..

RUN rm apps/worker/.env

EXPOSE 3001

CMD ["pnpm", "start:worker"]