apiVersion: apps/v1
kind: Deployment
metadata:
  name: xhip-worker
  labels:
    app: xhip-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xhip-worker
  template:
    metadata:
      labels:
        app: xhip-worker
    spec:
      containers:
        - name: xhip-worker
          image: rithik933/xhip-worker:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always